version: '3.5'
services:
  ktor-encryption-server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - data:/app/uploads
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: postgresql
    image: postgres:15.0
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
volumes:
  data:
  db: